export const experience = [
  {
    id: "1",
    logo: "",
    company: "Freelance",
    designation: "Frontend Developer",
    duration: "02.2026 - Present",
    location: "Kolkata, India",
    type: "Full-Time",
    description: [
      "Between gigs, I kept building. Nexus Dark started as a VS Code theme I made for myself and it now has 1.5k+ downloads on Open VSX, which still feels surreal.",
      "Sonner Patterns came out of frustration with copy-pasting toast logic across projects, so I turned it into an open source collection of production-ready patterns built on Sonner.",
      "Right now I'm deep in Sparkflo, a node-based canvas for building AI workflows with a focus on developer experience and visual clarity.",
      "I'm open to full-time roles and freelance work. Frontend is where I live, open source is where I think out loud.",
    ],
    tech: ["Next.js", "React", "TypeScript", "TailwindCSS", "Motion", "Vercel"],
  },

  {
    id: "2",
    logo: "https://media.licdn.com/dms/image/v2/C510BAQEFq9G1hU3-oA/company-logo_100_100/company-logo_100_100/0/1630571378203?e=1779321600&v=beta&t=Nm6o8_MfvpTy0DRFKTHr1KmH1t4li1oKfVE1U-J-Yck",
    company: "Klizo Solutions Pvt Ltd",
    designation: "Frontend Developer",
    duration: "09.2024 - 01.2026",
    location: "Kolkata, India",
    type: "Full-Time",
    description: [
      "Klizo was where I learned what shipping under real pressure actually feels like. Multiple client products, simultaneous deadlines, different design systems every time.",
      "Delivered 80% of an AI SaaS product's user-facing frontend with API integrations in under 24 hours, cutting delivery time by 40%.",
      "Built a admin panel for a SaaS product from scratch, covering auth, dashboards, and resume parsing. Handled 70% of the frontend myself and user engagement went up 35% after launch.",
      "Refactored an investor-facing SaaS into a modular React-Bootstrap architecture, improving load speed and UX flow by 30%.",
      "Built a marketing site from zero in vanilla JS and Tailwind, no framework overhead, shipped 40% faster than estimated.",
    ],
    tech: [
      "Next.js",
      "React",
      "TypeScript",
      "TailwindCSS",
      "Node.js",
      "Express.js",
      "Shadcn UI",
    ],
  },

  {
    id: "3",
    logo: "https://media.licdn.com/dms/image/v2/D4D0BAQGjKb2rERHHCA/company-logo_100_100/company-logo_100_100/0/1699957562283?e=1779321600&v=beta&t=ynGhIpkklKgpwT5oBtCuCZBHF0Qii80LwxzZAbGS9Gs",
    company: "Sikharthy Infotech Pvt. Ltd.",
    designation: "Software Engineer",
    duration: "06.2023 - 09.2024",
    location: "Kolkata, India",
    type: "Full-Time",
    description: [
      "This one was two jobs in one, building client-facing apps during the day and teaching the next wave of developers in structured sessions.",
      "Contributed to frontend builds across multiple client projects. Satisfaction ratings climbed 40% because the interfaces finally felt right to use.",
      "Taught 500+ students HTML, CSS, JavaScript, and React through project-based training, cutting their average learning curve by 30%.",
      "Designed curriculum from scratch for multiple cohorts, built to stick and not just to cover material. Engagement stayed high because the work felt real.",
    ],
    tech: ["React", "Node.js", "Express.js", "JavaScript", "HTML", "CSS"],
  },
];
